#pragma once

// Generated by write_version.sh
namespace BewaesserungVersion {
static constexpr const char* kBaseVersion = "0.2.0";
static constexpr const char* kGitHash = "55eaf828";
static constexpr const char* kBuildDate = "2026-05-13";
static constexpr const char* kFullVersion = "0.2.0+55eaf828";
}  // namespace BewaesserungVersion
