#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
VERSION_FILE="${SCRIPT_DIR}/VERSION"
HEADER_FILE="${SCRIPT_DIR}/Version.hpp"

if [[ ! -f "${VERSION_FILE}" ]]; then
  echo "0.0.0" > "${VERSION_FILE}"
fi

current_version="$(tr -d '[:space:]' < "${VERSION_FILE}")"
if [[ ! "${current_version}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
  echo "ERROR: ${VERSION_FILE} must contain semantic version MAJOR.MINOR.PATCH" >&2
  exit 1
fi

major="${BASH_REMATCH[1]}"
minor="${BASH_REMATCH[2]}"
patch="${BASH_REMATCH[3]}"

next_patch=$((patch + 1))
next_version="${major}.${minor}.${next_patch}"
echo "${next_version}" > "${VERSION_FILE}"

git_hash="nogit"
if git -C "${SCRIPT_DIR}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git_hash="$(git -C "${SCRIPT_DIR}" rev-parse --short=8 HEAD 2>/dev/null || true)"
  git_hash="${git_hash:-nogit}"
fi

build_date="$(date -u +%Y-%m-%d)"
full_version="${next_version}+${git_hash}"

tmp_header="${HEADER_FILE}.tmp"
cat > "${tmp_header}" <<EOF
#pragma once

// Generated by write_version.sh
namespace BewaesserungVersion {
static constexpr const char* kBaseVersion = "${next_version}";
static constexpr const char* kGitHash = "${git_hash}";
static constexpr const char* kBuildDate = "${build_date}";
static constexpr const char* kFullVersion = "${full_version}";
}  // namespace BewaesserungVersion
EOF

mv "${tmp_header}" "${HEADER_FILE}"
echo "Updated ${HEADER_FILE}: ${full_version}"
